//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenKeeper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ActionId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int UserId { get; set; }
    
        public virtual Actions Actions { get; set; }
        public virtual Fields Fields { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
