//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenKeeper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperties
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
