//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenKeeper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public long Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<long> PropertyId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Properties Properties { get; set; }
    }
}
