//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenKeeper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.AuditLog = new HashSet<AuditLog>();
            this.ProductImages = new HashSet<ProductImages>();
            this.ProductProperty = new HashSet<ProductProperty>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long MainPrice { get; set; }
        public Nullable<long> DiscountPrice { get; set; }
        public long Quantity { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ICollection<AuditLog> AuditLog { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        public virtual ICollection<ProductProperty> ProductProperty { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
