//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenKeeper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.AuditLog = new HashSet<AuditLog>();
            this.ProductProperties = new HashSet<ProductProperties>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> MainPrice { get; set; }

        public string FormattedMainPrice { get
            {
                string mainPriceStr = MainPrice.ToString();

                string rubles = mainPriceStr.Substring(0, mainPriceStr.Length - 2);
                string kopecks = mainPriceStr.Substring(mainPriceStr.Length - 2);
                return $"{rubles}.{kopecks} ₽";
            }
        }

        public Nullable<long> DiscountPrice { get; set; }

        public string FormattedDiscountPrice
        {
            get
            {
                if(DiscountPrice == null)
                {
                    return "";
                }
                string discountPriceStr = DiscountPrice.ToString();

                string rubles = discountPriceStr.Substring(0, discountPriceStr.Length - 2);
                string kopecks = discountPriceStr.Substring(discountPriceStr.Length - 2);
                return $"{rubles}.{kopecks} ₽";
            }
        }

        public Nullable<long> PriceToSort
        {
            get
            {
                if (DiscountPrice == null)
                {
                    return MainPrice;
                }
                return DiscountPrice;
            }
        }

        public long Quantity { get; set; }
        public int CategoryId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<AuditLog> AuditLog { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual ICollection<ProductProperties> ProductProperties { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
