//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenKeeper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public Properties()
        {
            this.ProductProperty = new HashSet<ProductProperty>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<ProductProperty> ProductProperty { get; set; }
    }
}
